#ifndef __uiLoggerA__
#define __uiLoggerA__

/**
@file
Subclass of LoggerA, which is generated by wxFormBuilder.
*/

#include "uiLogger.h"

//// end generated include

//x_#include "MyLibrary/Ctrl/AboutBox/wxMozillaLikeAboutBoxDialog.h"
#include "../../../Ctrl/AboutBox/wxMozillaLikeAboutBoxDialog.h"

/** Implementing LoggerA */
class uiLoggerA : public LoggerA
{
	protected:
		// Handlers for LoggerA events.
		void m_toolClearOnToolClicked( wxCommandEvent& event );
		void m_toolHideOnToolClicked( wxCommandEvent& event );
		void m_toolAboutOnToolClicked( wxCommandEvent& event );
	public:
		/** Constructor */
		uiLoggerA( wxWindow* parent );
	//// end generated class members

		void ToggleVisible();


};

#endif // __uiLoggerA__
