#ifndef __UIMainFrame__
#define __UIMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "UI.h"

//// end generated include

/** Implementing MainFrame */
class UIMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void m_button1OnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		UIMainFrame( wxWindow* parent );
	//// end generated class members






};

#endif // __UIMainFrame__
