#ifndef __UIMainFrame1__
#define __UIMainFrame1__

/**
@file
Subclass of MainFrame1, which is generated by wxFormBuilder.
*/

#include "UI.h"

//// end generated include

/** Implementing MainFrame1 */
class UIMainFrame1 : public MainFrame1
{
	public:
		/** Constructor */
		UIMainFrame1( wxWindow* parent );
	//// end generated class members











};

#endif // __UIMainFrame1__
