#ifndef __uiComboPanelA__
#define __uiComboPanelA__

/**
@file
Subclass of ComboPanelA, which is generated by wxFormBuilder.
*/

#include "uiComboPanel.h"

//// end generated include

/** Implementing ComboPanelA */
class uiComboPanelA : public ComboPanelA
{
	protected:
		// Handlers for ComboPanelA events.
		void onAdd( wxCommandEvent& event );
	public:
		/** Constructor */
		uiComboPanelA( wxWindow* parent );
	//// end generated class members
	
		// wxComboBox compatible ctor
		uiComboPanelA(wxWindow *parent,
	               wxWindowID id,
	               const wxString& value = wxEmptyString,
	               const wxPoint& pos = wxDefaultPosition,
	               const wxSize& size = wxDefaultSize,
	               int n = 0, const wxString choices[] = NULL,
	               long style = 0,
	               const wxValidator& validator = wxDefaultValidator,
	               const wxString& name = wxComboBoxNameStr);

};

#endif // __uiComboPanelA__
