#ifndef __dlgFieldEditor__
#define __dlgFieldEditor__

/**
@file
Subclass of FieldEditor, which is generated by wxFormBuilder.
*/

#include "dlg.h"

//// end generated include

//x_#include "MyLibrary/Base/ClientData.h"
#include "../../Base/ClientData.h"


/** Implementing FieldEditor */
class dlgFieldEditor : public FieldEditor
{
	protected:
		// Handlers for FieldEditor events.
		void xClose( wxCloseEvent& event );
		void onSave( wxCommandEvent& event );
		void onReset( wxCommandEvent& event );
		void onClose( wxCommandEvent& event );
	public:
		/** Constructor */
		dlgFieldEditor( wxWindow* parent );
	//// end generated class members
	
		// wxDialog ctor compatiable
		dlgFieldEditor( wxWindow *parent, wxWindowID id,
		            const wxString &title,
		            const wxPoint &pos = wxDefaultPosition,
		            const wxSize &size = wxDefaultSize,
		            long style = wxDEFAULT_DIALOG_STYLE,
		            const wxString &name = wxDialogNameStr );

		virtual int ShowModal( AppDB* db, wxString table, wxString key_column, wxString val_column );

	protected:
		bool doLayout(wxDialog* dlg);

	private:
		void init();
		wxString m_val_column;
		wxString m_key_column;

};

#endif // __dlgFieldEditor__
