#ifndef __dlgRecordEditor__
#define __dlgRecordEditor__

/**
@file
Subclass of RecordEditor, which is generated by wxFormBuilder.
*/

#include "dlg.h"

//// end generated include

#include "../../Ctrl/StatusBar/StatusBar.h"
#include "../../Base/ClientData.h"

class dlgRecordEditor;
wxDECLARE_EVENT( wxRECORD_CHANGED, wxCommandEvent );
wxDECLARE_EVENT( wxRECORD_APPENDED, wxCommandEvent );

/** Implementing RecordEditor */
class dlgRecordEditor : public RecordEditor
{
	protected:
		// Handlers for RecordEditor events.
		void xClose( wxCloseEvent& event );
		void onInitDialog( wxInitDialogEvent& event );
		void onSave( wxCommandEvent& event );
		void onReset( wxCommandEvent& event );
		void onClose( wxCommandEvent& event );
	public:
		/** Constructor */
		dlgRecordEditor( wxWindow* parent );
	//// end generated class members

		// wxDialog ctor compatible
		dlgRecordEditor( wxWindow *parent, wxWindowID id,
	            const wxString &title,
	            const wxPoint &pos = wxDefaultPosition,
	            const wxSize &size = wxDefaultSize,
	            long style = wxDEFAULT_DIALOG_STYLE,
	            const wxString &name = wxDialogNameStr );

		//int ShowModal( AppDB* db, wxString table, wxString where="0" );
		virtual void SetTitle( const wxString &title );

	protected:
		bool doLayout(wxDialog* dlg);

	private:
		void init();


};

#endif // __dlgRecordEditor__
