#ifndef __dlgRecordManager__
#define __dlgRecordManager__

/**
@file
Subclass of RecordManager, which is generated by wxFormBuilder.
*/

#include "dlg.h"

//// end generated include

//x_#include "MyLibrary/Ctrl/DataViewCtrl/DataViewCtrl.h"
#include "../../Ctrl/DataViewCtrl/DataViewCtrl.h"
#include "dlgRecordEditor.h"
//x_#include "MyLibrary/Base/ClientData.h"
#include "../../Base/ClientData.h"

/** Implementing RecordManager */
class dlgRecordManager : public RecordManager
{
	protected:
		// Handlers for RecordManager events.
		void xClose( wxCloseEvent& event );
		void onAdd( wxCommandEvent& event );
		void onEdit( wxCommandEvent& event );
		void onDelete( wxCommandEvent& event );
		void onRefresh( wxCommandEvent& event );
		void onClose( wxCommandEvent& event );
		void onDataViewCtrlSelectionChanged( wxDataViewEvent& event );
	public:
		/** Constructor */
		dlgRecordManager( wxWindow* parent );
	//// end generated class members

		// wxDialog ctor compatible
		dlgRecordManager( wxWindow *parent, wxWindowID id,
	            const wxString &title,
	            const wxPoint &pos = wxDefaultPosition,
	            const wxSize &size = wxDefaultSize,
	            long style = wxDEFAULT_DIALOG_STYLE,
	            const wxString &name = wxDialogNameStr );

		//virtual int ShowModal( AppDB* db, wxString table, wxString columns, wxString where="1", wxString orderby="", int limit=-1, int offset=-1 ) = 0;

	protected:
		// event handler when db/table updated or inserted
		virtual void onRecordChanged( wxCommandEvent& event );
		virtual void onRecordAppended( wxCommandEvent& event );

		wxDECLARE_EVENT_TABLE();

		//virtual int showMe( AppDB* db, wxString table, wxString columns, wxString where="1", wxString orderby="", int limit=-1, int offset=-1 );
		void x_doModified( dlgRecordEditor* form, wxString where );
		void showFormEdit( dlgRecordEditor* form, wxString title="Edit" );
		void showFormAdd( dlgRecordEditor* form, wxString title="Add" );

		// these method should be implemented on derived class
		//virtual void action_BeforeDelete_Record();
		//virtual void action_AfterDelete_Record();

		dlgRecordEditor* m_editorForm;









};

#endif // __dlgRecordManager__
