#ifndef __CtrlLog__
#define __CtrlLog__

/**
@file
Subclass of Log, which is generated by wxFormBuilder.
*/

#include "Ctrl.h"

//// end generated include

//#include <wx/wx.h>

/** Implementing Log */
class CtrlLog : public Log
{
	protected:
		// Handlers for Log events.
		void m_toolClearOnToolClicked( wxCommandEvent& event );
		void m_toolHideOnToolClicked( wxCommandEvent& event );
		void m_toolAboutOnToolClicked( wxCommandEvent& event );
	public:
		/** Constructor */
		CtrlLog( wxWindow* parent );
	//// end generated class members
		CtrlLog(wxWindow *parent, wxWindowID winid = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = wxTAB_TRAVERSAL | wxNO_BORDER, const wxString& name = wxPanelNameStr);
		~CtrlLog();

		void SetVisible();










};

#endif // __CtrlLog__
