#ifndef __CtrlImage__
#define __CtrlImage__

/**
@file
Subclass of Image, which is generated by wxFormBuilder.
*/

#include "Ctrl.h"

//// end generated include

//#include <wx/wx.h>
//#include "Common/Global_Var.h"

#define DATADIR			wxString::Format( "%s/Data/", m_config->GetMyDir() )
//#define NOIMGFILE		wxString::Format( "%s/Data/noimage.png", conv->GetMyDir() )
//#define PF				wxLogMessage(__PRETTY_FUNCTION__)
#define NOIMAGE			"noimage.png"

/** Implementing Image */
class CtrlImage : public Image
{
	protected:
		// Handlers for Image events.
		void m_textLabelOnText( wxCommandEvent& event );
		void m_toolBrowseOnToolClicked( wxCommandEvent& event );
		void m_toolClearOnToolClicked( wxCommandEvent& event );
	public:
		/** Constructor */
		CtrlImage( wxWindow* parent );
	//// end generated class members
		CtrlImage(wxWindow *parent, wxWindowID winid = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = wxTAB_TRAVERSAL | wxNO_BORDER, const wxString& name = wxPanelNameStr);

		virtual void SetLabel(const wxString& label);
		virtual wxString GetLabel() const;

	private:
		//bool m_bnew_file;			// Ddy: to identified if the fila already altered by user
		//wxString m_displayed_file;	// dir+fname
		//wxString m_currentfilename;		// fname+dir
		//bool m_newfile;
		wxString m_dir;
		wxString m_filename;
		wxString m_oldfilename;

		void setImage(wxString filename);
		void clearImage();













};

#endif // __CtrlImage__
