#ifndef __RSDialogLogin__
#define __RSDialogLogin__

/**
@file
Subclass of DialogLogin, which is generated by wxFormBuilder.
*/

#include "RS.h"

//// end generated include

/** Implementing DialogLogin */
class RSDialogLogin : public DialogLogin
{
	public:
		/** Constructor */
		RSDialogLogin( wxWindow* parent );
	//// end generated class members
	
};

#endif // __RSDialogLogin__
