#ifndef __RSDialogNewPatient__
#define __RSDialogNewPatient__

/**
@file
Subclass of DialogNewPatient, which is generated by wxFormBuilder.
*/

#include "RS.h"

//// end generated include

#include <DB/AppDB.h>
#include <DdyLib.wx.h>

#define MYTABLE             "rs_patient"

/** Implementing DialogNewPatient */
class RSDialogNewPatient : public DialogNewPatient
{
	protected:
		// Handlers for DialogNewPatient events.
		void dateBirthOnDateChanged( wxDateEvent& event );
		void buttonSaveOnButtonClick( wxCommandEvent& event );
		void buttonRegisterOnButtonClick( wxCommandEvent& event );
		void buttonUpdateOnButtonClick( wxCommandEvent& event );
		void buttonResetOnButtonClick( wxCommandEvent& event );
		void buttonCloseOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		RSDialogNewPatient( wxWindow* parent );
	//// end generated class members
                
                void Tampil( int rcd_id );

        private:
            int m_rcd_id;
            int m_action; // wxID_ADD atau wx_ID_EDIT
            int m_stbFldCnt;
            wxString m_info1;
            AppDB* m_db;
            void makeAge();




};

#endif // __RSDialogNewPatient__
