#ifndef __RSMainFrame__
#define __RSMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "RS.h"

//// end generated include

#include "RSDialogNewPatient.h"
#include <DB/AppDB.h>

/** Implementing MainFrame */
class RSMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void menuPendaftaranPasienOnMenuSelection( wxCommandEvent& event );
		void m_button6OnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		RSMainFrame( wxWindow* parent );
	//// end generated class members

                AppDB* m_db;
























};

#endif // __RSMainFrame__
