#ifndef __uiImagePickerA__
#define __uiImagePickerA__

/**
@file
Subclass of ImagePickerA, which is generated by wxFormBuilder.
*/

#include "uiImagePicker.h"

//// end generated include

#include "images/noimage1.h"
#include "images/badimage1.h"
#include "images/No_Image_Available.h"

//#define DATADIR			wxString::Format( "%s/Data/", m_config->GetMyDir() )
#define DATADIR			wxString::Format( "%s/Data/", "./" )
//#define NOIMGFILE		wxString::Format( "%s/Data/noimage.png", conv->GetMyDir() )
//#define PF			wxLogMessage(__PRETTY_FUNCTION__)
#define NOIMAGE			"noimage.png"

/** Implementing ImagePickerA */
class uiImagePickerA : public ImagePickerA
{
	protected:
		// Handlers for ImagePickerA events.
		void m_textLabelOnText( wxCommandEvent& event );
		void onBrowse( wxCommandEvent& event );
		void onClear( wxCommandEvent& event );
	public:
		/** Constructor */
		uiImagePickerA( wxWindow* parent );
	//// end generated class members

		// wxPanel compatible ctor
		uiImagePickerA(wxWindow *parent,
	            wxWindowID winid = wxID_ANY,
	            const wxPoint& pos = wxDefaultPosition,
	            const wxSize& size = wxDefaultSize,
	            long style = wxTAB_TRAVERSAL | wxNO_BORDER,
	            const wxString& name = wxPanelNameStr);

		virtual void SetLabel(const wxString& label);
		virtual wxString GetLabel() const;

	private:
		//bool m_bnew_file;			// Ddy: to identified if the fila already altered by user
		//wxString m_displayed_file;	// dir+fname
		//wxString m_currentfilename;		// fname+dir
		//bool m_newfile;
		wxString m_dir;
		wxString m_filename;
		wxString m_oldfilename;

		void setImage(wxString filename);
		void setImage2(wxString filename); // Ddy: ratio altered


};

#endif // __uiImagePickerA__
